name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: VITE_BASE_PATH=yarn install --frozen-lockfile

      - name: Build project
        run: VITE_BASE_PATH="/locked-media-browser/" yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          branch: gh-pages
